apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  labels:
    name: analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: analytics-api
  template:
    metadata:
      labels:
        service: analytics-api
    spec:
      containers:
      - name: app
        image: "006712159429.dkr.ecr.us-east-1.amazonaws.com/udacity-project:13"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: POSTGRES_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: POSTGRES_PASSWORD
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: APP_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: DB_NAME

      restartPolicy: Always
