apiVersion: v1
kind: Service
metadata:
  name: analytics-api
spec:
  selector:
    app.kubernetes.io/name: analytics-api
  ports:
  - name: "app-port"
    protocol: TCP
    port: 5153  # Use the value as a string
    targetPort: 5153  # Use the value as a string
